// Code generated by MockGen. DO NOT EDIT.
// Source: k8s.io/cri-api/pkg/apis/runtime/v1 (interfaces: RuntimeService_GetContainerEventsServer)
//
// Generated by this command:
//
//	mockgen -package containereventservermock -destination ./test/mocks/containereventserver/containereventserver.go k8s.io/cri-api/pkg/apis/runtime/v1 RuntimeService_GetContainerEventsServer
//

// Package containereventservermock is a generated GoMock package.
package containereventservermock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	metadata "google.golang.org/grpc/metadata"
	v1 "k8s.io/cri-api/pkg/apis/runtime/v1"
)

// MockRuntimeService_GetContainerEventsServer is a mock of RuntimeService_GetContainerEventsServer interface.
type MockRuntimeService_GetContainerEventsServer[Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeService_GetContainerEventsServerMockRecorder[Res]
	isgomock struct{}
}

// MockRuntimeService_GetContainerEventsServerMockRecorder is the mock recorder for MockRuntimeService_GetContainerEventsServer.
type MockRuntimeService_GetContainerEventsServerMockRecorder[Res any] struct {
	mock *MockRuntimeService_GetContainerEventsServer[Res]
}

// NewMockRuntimeService_GetContainerEventsServer creates a new mock instance.
func NewMockRuntimeService_GetContainerEventsServer[Res any](ctrl *gomock.Controller) *MockRuntimeService_GetContainerEventsServer[Res] {
	mock := &MockRuntimeService_GetContainerEventsServer[Res]{ctrl: ctrl}
	mock.recorder = &MockRuntimeService_GetContainerEventsServerMockRecorder[Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeService_GetContainerEventsServer[Res]) EXPECT() *MockRuntimeService_GetContainerEventsServerMockRecorder[Res] {
	return m.recorder
}

// Context mocks base method.
func (m *MockRuntimeService_GetContainerEventsServer[Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockRuntimeService_GetContainerEventsServerMockRecorder[Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockRuntimeService_GetContainerEventsServer[Res])(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockRuntimeService_GetContainerEventsServer[Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockRuntimeService_GetContainerEventsServerMockRecorder[Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockRuntimeService_GetContainerEventsServer[Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockRuntimeService_GetContainerEventsServer[Res]) Send(arg0 *v1.ContainerEventResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockRuntimeService_GetContainerEventsServerMockRecorder[Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockRuntimeService_GetContainerEventsServer[Res])(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockRuntimeService_GetContainerEventsServer[Res]) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockRuntimeService_GetContainerEventsServerMockRecorder[Res]) SendHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockRuntimeService_GetContainerEventsServer[Res])(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockRuntimeService_GetContainerEventsServer[Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockRuntimeService_GetContainerEventsServerMockRecorder[Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockRuntimeService_GetContainerEventsServer[Res])(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockRuntimeService_GetContainerEventsServer[Res]) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockRuntimeService_GetContainerEventsServerMockRecorder[Res]) SetHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockRuntimeService_GetContainerEventsServer[Res])(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockRuntimeService_GetContainerEventsServer[Res]) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockRuntimeService_GetContainerEventsServerMockRecorder[Res]) SetTrailer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockRuntimeService_GetContainerEventsServer[Res])(nil).SetTrailer), arg0)
}
