---
codecov:
  notify:
    after_n_builds: 1
    require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: 50..75

  status:
    project: true
    patch: true
    changes: false

comment:
  layout: "header, diff"
  behavior: default
  require_changes: false
