---
run:
  build-tags:
    - apparmor
    - containers_image_ostree_stub
    # containers/image would use mtrmac/gpgme otherwise, which requires gpgme C headers
    - containers_image_openpgp
    - selinux
    - test
    # needs btrfs headers installed
    - exclude_graphdriver_btrfs
    # needs devmapper headers installed
    - exclude_graphdriver_devicemapper
  concurrency: 6
  deadline: 10m
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - execinquery
    - exportloopref
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - goprintffuncname
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - logrlint
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nosprintfhostport
    - prealloc
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tenv
    - testableexamples
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
    - zerologlint
    # - containedctx
    # - contextcheck
    # - cyclop
    # - depguard
    # - errname
    # - errorlint
    # - exhaustive
    # - exhaustruct
    # - forbidigo
    # - funlen
    # - gci
    # - ginkgolinter
    # - gochecknoglobals
    # - gocognit
    # - godot
    # - godox
    # - goerr113
    # - gomnd
    # - gomoddirectives
    # - gomodguard
    # - gosec
    # - interfacebloat
    # - ireturn
    # - lll
    # - maintidx
    # - nestif
    # - nilerr
    # - nilnil
    # - nlreturn
    # - noctx
    # - nolintlint
    # - nonamedreturns
    # - paralleltest
    # - predeclared
    # - promlinter
    # - revive
    # - tagliatelle
    # - testpackage
    # - thelper
    # - varnamelen
    # - wastedassign
    # - wrapcheck
    # - wsl
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-checks:
      # Diagnostic
      - appendAssign
      - appendCombine
      - argOrder
      - assignOp
      - badCall
      - badCond
      - badLock
      - badRegexp
      - badSorting
      - boolExprSimplify
      - builtinShadow
      - builtinShadowDecl
      - captLocal
      - caseOrder
      - codegenComment
      - commentFormatting
      - commentedOutCode
      - commentedOutImport
      - defaultCaseOrder
      - deferInLoop
      - deferUnlambda
      - deprecatedComment
      - docStub
      - dupArg
      - dupBranchBody
      - dupCase
      - dupImport
      - dupSubExpr
      - dynamicFmtString
      - elseif
      - emptyDecl
      - emptyFallthrough
      - emptyStringTest
      - equalFold
      - evalOrder
      - exitAfterDefer
      - exposedSyncMutex
      - externalErrorReassign
      - flagDeref
      - flagName
      - hexLiteral
      - httpNoBody
      - hugeParam
      - ifElseChain
      - importShadow
      - indexAlloc
      - initClause
      - mapKey
      - methodExprCall
      - nestingReduce
      - newDeref
      - nilValReturn
      - octalLiteral
      - offBy1
      - paramTypeCombine
      - preferDecodeRune
      - preferFilepathJoin
      - preferFprint
      - preferStringWriter
      - preferWriteByte
      - ptrToRefParam
      - rangeExprCopy
      - rangeValCopy
      - redundantSprint
      - regexpMust
      - regexpPattern
      - regexpSimplify
      - returnAfterHttpError
      - ruleguard
      - singleCaseSwitch
      - sliceClear
      - sloppyLen
      - sloppyReassign
      - sloppyTestFuncName
      - sloppyTypeAssert
      - sortSlice
      - sprintfQuotedString
      - sqlQuery
      - stringConcatSimplify
      - stringXbytes
      - stringsCompare
      - switchTrue
      - syncMapLoadAndDelete
      - timeCmpSimplify
      - timeExprSimplify
      - todoCommentWithoutDetail
      - tooManyResultsChecker
      - truncateCmp
      - typeAssertChain
      - typeDefFirst
      - typeSwitchVar
      - typeUnparen
      - uncheckedInlineErr
      - underef
      - unlabelStmt
      - unlambda
      - unnamedResult
      - unnecessaryBlock
      - unnecessaryDefer
      - unslice
      - valSwap
      - weakCond
      - wrapperFunc
      - yodaStyleExpr
      # - filepathJoin
      # - whyNoLint
  gocyclo:
    min-complexity: 154
  nakedret:
    max-func-lines: 15
