---
run:
  build-tags:
    - apparmor
    - containers_image_ostree_stub
    # containers/image would use mtrmac/gpgme otherwise, which requires gpgme C headers
    - containers_image_openpgp
    - selinux
    - test
    # needs btrfs headers installed
    - exclude_graphdriver_btrfs
    # needs devmapper headers installed
    - exclude_graphdriver_devicemapper
    # remove this tag when golangci lint supports go 1.18 and generics                                                                                                   │noctx: noctx finds sending http request without context.Context [fast: false, auto-fix: false]
    - skip_pod_runtime
  concurrency: 6
  deadline: 5m
linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - exportloopref
    - forcetypeassert
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tenv
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    # - containedctx
    # - contextcheck
    # - cyclop
    # - errname
    # - errorlint
    # - exhaustive
    # - exhaustivestruct
    # - forbidigo
    # - funlen
    # - gci
    # - gochecknoglobals
    # - gocognit
    # - godot
    # - godox
    # - goerr113
    # - gomnd
    # - gomoddirectives
    # - gomodguard
    # - gosec
    # - ifshort
    # - ireturn
    # - lll
    # - maintidx
    # - nestif
    # - nilerr
    # - nilnil
    # - nlreturn
    # - noctx
    # - paralleltest
    # - predeclared
    # - promlinter
    # - revive
    # - tagliatelle
    # - testpackage
    # - thelper
    # - varnamelen
    # - wastedassign
    # - wrapcheck
    # - wsl
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-checks:
      # Diagnostic
      - appendAssign
      - argOrder
      - badCall
      - badCond
      - badLock
      - badRegexp
      - badSorting
      - builtinShadowDecl
      - caseOrder
      - codegenComment
      - commentedOutCode
      - deferInLoop
      - deprecatedComment
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - dynamicFmtString
      - emptyDecl
      - evalOrder
      - exitAfterDefer
      - externalErrorReassign
      - flagDeref
      - flagName
      - mapKey
      - nilValReturn
      - offBy1
      - regexpPattern
      - returnAfterHttpError
      - sloppyReassign
      - sloppyTypeAssert
      - sortSlice
      - sprintfQuotedString
      - sqlQuery
      - syncMapLoadAndDelete
      - truncateCmp
      - unnecessaryDefer
      - weakCond
      # - filepathJoin

      # Performance
      - appendCombine
      - equalFold
      - hugeParam
      - indexAlloc
      - preferDecodeRune
      - preferFprint
      - preferStringWriter
      - preferWriteByte
      - rangeExprCopy
      - rangeValCopy
      - sliceClear
      - stringXbytes

      # Style
      - assignOp
      - boolExprSimplify
      - captLocal
      - commentFormatting
      - commentedOutImport
      - defaultCaseOrder
      - deferUnlambda
      - docStub
      - dupImport
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - exposedSyncMutex
      - hexLiteral
      - httpNoBody
      - ifElseChain
      - methodExprCall
      - newDeref
      - octalLiteral
      - preferFilepathJoin
      - redundantSprint
      - regexpMust
      - regexpSimplify
      - ruleguard
      - singleCaseSwitch
      - sloppyLen
      - stringConcatSimplify
      - switchTrue
      - timeExprSimplify
      - tooManyResultsChecker
      - typeAssertChain
      - typeDefFirst
      - typeSwitchVar
      - underef
      - unlabelStmt
      - unlambda
      - unslice
      - valSwap
      - wrapperFunc
      - yodaStyleExpr
      - ioutilDeprecated
      # - whyNoLint

      # Opinionated
      - builtinShadow
      - importShadow
      - initClause
      - nestingReduce
      - paramTypeCombine
      - ptrToRefParam
      - typeUnparen
      - unnamedResult
      - unnecessaryBlock
  gocyclo:
    min-complexity: 141
  nakedret:
    max-func-lines: 15
