{
 "title": "CRI-O",
 "description": "CRI-O Metrics Dashboard",
 "tags": [
  "cri-o",
  "container runtime",
  "runtime",
  "node"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Selected Nodes",
    "query": "container_runtime_crio_operations"
   }
  ]
 },
 "panels": [
  {
   "title": "CRI-O Operations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_runtime_crio_operations{instance=~\"$node\"}[5m])",
     "legendFormat": "{{instance}} - {{operation_type}}"
    }
   ]
  },
  {
   "title": "CRI-O Operations Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_runtime_crio_operations_errors{instance=~\"$node\"}[5m])",
     "legendFormat": "{{instance}} - {{operation_type}}"
    }
   ]
  },
  {
   "title": "CRI-O Operations Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 68 },
   "repeat": "node",
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": " rate(container_runtime_crio_operations_latency_microseconds_count{instance=~\"$node\"}[5m])",
     "legendFormat": "{{instance}} - {{operation_type}}"
    }
   ]
  }
 ]
}