#!/usr/bin/env bash
set -euo pipefail

# Global vars to be used
# shellcheck source=vars
source "$(dirname "${BASH_SOURCE[0]}")"/vars

cd "$(dirname "$0")"

CONMON_VERSION=v2.0.11
RUNC_VERSION=v1.0.0-rc10
CNI_PLUGINS_VERSION=v0.8.5
CRICTL_VERSION=v1.17.0

FILES_BIN=(
    "../bin/crio-status-x86_64-static-glibc"
    "../bin/crio-status-x86_64-static-musl"
    "../bin/crio-x86_64-static-glibc"
    "../bin/crio-x86_64-static-musl"
    "../bin/pinns"
)
FILES_MAN=(
    "../docs/crio.8"
    "../docs/crio.conf.5"
    "../docs/crio.conf.d.5"
)
FILES_ETC=(
    "../crictl.yaml"
    "../crio-umount.conf"
    "../crio.conf"
)
FILES_CONTRIB=(
    "../contrib/cni/10-crio-bridge.conf"
    "../contrib/policy.json"
    "../contrib/systemd/crio-shutdown.service"
    "../contrib/systemd/crio-wipe.service"
    "../contrib/systemd/crio.service"
)
COMPLETIONS="../completions"

TMPDIR=tmp
rm -rf $TMPDIR
mkdir -p $TMPDIR/{bin,contrib,etc,man}

cp -r $COMPLETIONS $TMPDIR

ERRORED=0
for FILE in "${FILES_BIN[@]}"; do
    if [[ ! -f "$FILE" ]]; then
        echo "File '$FILE' does not exist"
        ERRORED=1
    elif [[ ! -x "$FILE" ]]; then
        echo "File '$FILE' is not exectuable"
        ERRORED=1
    elif ! file "$FILE" | grep "statically linked" | grep -q stripped; then
        echo "Binary '$FILE' is not statically linked and stripped"
        ERRORED=1
    else
        cp "$FILE" $TMPDIR/bin
    fi
done

for FILE in "${FILES_MAN[@]}"; do
    if [[ ! -f "$FILE" ]]; then
        echo "File '$FILE' does not exist"
        ERRORED=1
    else
        cp "$FILE" $TMPDIR/man
    fi
done

for FILE in "${FILES_ETC[@]}"; do
    if [[ ! -f "$FILE" ]]; then
        echo "File '$FILE' does not exist"
        ERRORED=1
    else
        cp "$FILE" $TMPDIR/etc
    fi
done
for FILE in "${FILES_CONTRIB[@]}"; do
    if [[ ! -f "$FILE" ]]; then
        echo "File '$FILE' does not exist"
        ERRORED=1
    else
        cp "$FILE" $TMPDIR/contrib
    fi
done

if [[ $ERRORED == 1 ]]; then
    exit 1
fi

# Local assets
cp Makefile $TMPDIR
cp README.md $TMPDIR

curl_to() {
    curl -sfL -o "$1" "$2"
}
TMP_BIN=$TMPDIR/bin

# conmon
curl_to $TMP_BIN/conmon \
    https://github.com/containers/conmon/releases/download/$CONMON_VERSION/conmon
chmod +x $TMP_BIN/conmon

# runc
curl_to $TMP_BIN/runc \
    https://github.com/opencontainers/runc/releases/download/$RUNC_VERSION/runc.amd64
chmod +x $TMP_BIN/runc

# CNI plugins
mkdir -p "$TMPDIR"/cni-plugins
set -x
curl_to - \
    https://github.com/containernetworking/plugins/releases/download/$CNI_PLUGINS_VERSION/cni-plugins-linux-amd64-$CNI_PLUGINS_VERSION.tgz |
    tar xfz - -C "$TMPDIR"/cni-plugins

# crictl
curl_to - \
    https://github.com/kubernetes-sigs/cri-tools/releases/download/$CRICTL_VERSION/crictl-$CRICTL_VERSION-linux-amd64.tar.gz |
    tar xfz - -C "$TMP_BIN"

# Create the archive
BUNDLE=crio-$(git describe --tags --exact-match 2>/dev/null || git rev-parse --short HEAD)
ARCHIVE="$BUNDLE.tar.gz"
rm -f "$ARCHIVE"
tar cfz "$ARCHIVE" tmp --transform s/tmp/"$BUNDLE"/
rm -rf tmp
echo "Created $(pwd)/$ARCHIVE"

# Test the archive
echo "Testing archive"
tar xf "$ARCHIVE"
pushd "$BUNDLE"
make DESTDIR=test
popd
rm -rf "$BUNDLE"
