// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cri-o/cri-o/internal/config/cgmgr (interfaces: CgroupManager)
//
// Generated by this command:
//
//	mockgen -package cgmgr -destination ./test/mocks/config/cgmgr/cgmgr.go github.com/cri-o/cri-o/internal/config/cgmgr CgroupManager
//

// Package cgmgr is a generated GoMock package.
package cgmgr

import (
	reflect "reflect"

	stats "github.com/cri-o/cri-o/internal/lib/stats"
	cgroups "github.com/opencontainers/cgroups"
	specs "github.com/opencontainers/runtime-spec/specs-go"
	gomock "go.uber.org/mock/gomock"
)

// MockCgroupManager is a mock of CgroupManager interface.
type MockCgroupManager struct {
	ctrl     *gomock.Controller
	recorder *MockCgroupManagerMockRecorder
	isgomock struct{}
}

// MockCgroupManagerMockRecorder is the mock recorder for MockCgroupManager.
type MockCgroupManagerMockRecorder struct {
	mock *MockCgroupManager
}

// NewMockCgroupManager creates a new mock instance.
func NewMockCgroupManager(ctrl *gomock.Controller) *MockCgroupManager {
	mock := &MockCgroupManager{ctrl: ctrl}
	mock.recorder = &MockCgroupManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCgroupManager) EXPECT() *MockCgroupManagerMockRecorder {
	return m.recorder
}

// ContainerCgroupAbsolutePath mocks base method.
func (m *MockCgroupManager) ContainerCgroupAbsolutePath(arg0, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerCgroupAbsolutePath", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerCgroupAbsolutePath indicates an expected call of ContainerCgroupAbsolutePath.
func (mr *MockCgroupManagerMockRecorder) ContainerCgroupAbsolutePath(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerCgroupAbsolutePath", reflect.TypeOf((*MockCgroupManager)(nil).ContainerCgroupAbsolutePath), arg0, arg1)
}

// ContainerCgroupManager mocks base method.
func (m *MockCgroupManager) ContainerCgroupManager(sbParent, containerID string) (cgroups.Manager, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerCgroupManager", sbParent, containerID)
	ret0, _ := ret[0].(cgroups.Manager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerCgroupManager indicates an expected call of ContainerCgroupManager.
func (mr *MockCgroupManagerMockRecorder) ContainerCgroupManager(sbParent, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerCgroupManager", reflect.TypeOf((*MockCgroupManager)(nil).ContainerCgroupManager), sbParent, containerID)
}

// ContainerCgroupPath mocks base method.
func (m *MockCgroupManager) ContainerCgroupPath(arg0, arg1 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerCgroupPath", arg0, arg1)
	ret0, _ := ret[0].(string)
	return ret0
}

// ContainerCgroupPath indicates an expected call of ContainerCgroupPath.
func (mr *MockCgroupManagerMockRecorder) ContainerCgroupPath(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerCgroupPath", reflect.TypeOf((*MockCgroupManager)(nil).ContainerCgroupPath), arg0, arg1)
}

// ContainerCgroupStats mocks base method.
func (m *MockCgroupManager) ContainerCgroupStats(sbParent, containerID string) (*stats.CgroupStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainerCgroupStats", sbParent, containerID)
	ret0, _ := ret[0].(*stats.CgroupStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainerCgroupStats indicates an expected call of ContainerCgroupStats.
func (mr *MockCgroupManagerMockRecorder) ContainerCgroupStats(sbParent, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainerCgroupStats", reflect.TypeOf((*MockCgroupManager)(nil).ContainerCgroupStats), sbParent, containerID)
}

// CreateSandboxCgroup mocks base method.
func (m *MockCgroupManager) CreateSandboxCgroup(sbParent, containerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSandboxCgroup", sbParent, containerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSandboxCgroup indicates an expected call of CreateSandboxCgroup.
func (mr *MockCgroupManagerMockRecorder) CreateSandboxCgroup(sbParent, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSandboxCgroup", reflect.TypeOf((*MockCgroupManager)(nil).CreateSandboxCgroup), sbParent, containerID)
}

// ExecCgroupManager mocks base method.
func (m *MockCgroupManager) ExecCgroupManager(cgroupPath string) (cgroups.Manager, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecCgroupManager", cgroupPath)
	ret0, _ := ret[0].(cgroups.Manager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecCgroupManager indicates an expected call of ExecCgroupManager.
func (mr *MockCgroupManagerMockRecorder) ExecCgroupManager(cgroupPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecCgroupManager", reflect.TypeOf((*MockCgroupManager)(nil).ExecCgroupManager), cgroupPath)
}

// IsSystemd mocks base method.
func (m *MockCgroupManager) IsSystemd() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSystemd")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSystemd indicates an expected call of IsSystemd.
func (mr *MockCgroupManagerMockRecorder) IsSystemd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSystemd", reflect.TypeOf((*MockCgroupManager)(nil).IsSystemd))
}

// MoveConmonToCgroup mocks base method.
func (m *MockCgroupManager) MoveConmonToCgroup(cid, cgroupParent, conmonCgroup string, pid int, resources *specs.LinuxResources) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveConmonToCgroup", cid, cgroupParent, conmonCgroup, pid, resources)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveConmonToCgroup indicates an expected call of MoveConmonToCgroup.
func (mr *MockCgroupManagerMockRecorder) MoveConmonToCgroup(cid, cgroupParent, conmonCgroup, pid, resources any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveConmonToCgroup", reflect.TypeOf((*MockCgroupManager)(nil).MoveConmonToCgroup), cid, cgroupParent, conmonCgroup, pid, resources)
}

// Name mocks base method.
func (m *MockCgroupManager) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockCgroupManagerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockCgroupManager)(nil).Name))
}

// PodAndContainerCgroupManagers mocks base method.
func (m *MockCgroupManager) PodAndContainerCgroupManagers(sbParent, containerID string) (cgroups.Manager, []cgroups.Manager, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PodAndContainerCgroupManagers", sbParent, containerID)
	ret0, _ := ret[0].(cgroups.Manager)
	ret1, _ := ret[1].([]cgroups.Manager)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PodAndContainerCgroupManagers indicates an expected call of PodAndContainerCgroupManagers.
func (mr *MockCgroupManagerMockRecorder) PodAndContainerCgroupManagers(sbParent, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PodAndContainerCgroupManagers", reflect.TypeOf((*MockCgroupManager)(nil).PodAndContainerCgroupManagers), sbParent, containerID)
}

// RemoveContainerCgManager mocks base method.
func (m *MockCgroupManager) RemoveContainerCgManager(containerID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveContainerCgManager", containerID)
}

// RemoveContainerCgManager indicates an expected call of RemoveContainerCgManager.
func (mr *MockCgroupManagerMockRecorder) RemoveContainerCgManager(containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveContainerCgManager", reflect.TypeOf((*MockCgroupManager)(nil).RemoveContainerCgManager), containerID)
}

// RemoveSandboxCgManager mocks base method.
func (m *MockCgroupManager) RemoveSandboxCgManager(sbID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveSandboxCgManager", sbID)
}

// RemoveSandboxCgManager indicates an expected call of RemoveSandboxCgManager.
func (mr *MockCgroupManagerMockRecorder) RemoveSandboxCgManager(sbID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSandboxCgManager", reflect.TypeOf((*MockCgroupManager)(nil).RemoveSandboxCgManager), sbID)
}

// RemoveSandboxCgroup mocks base method.
func (m *MockCgroupManager) RemoveSandboxCgroup(sbParent, containerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSandboxCgroup", sbParent, containerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSandboxCgroup indicates an expected call of RemoveSandboxCgroup.
func (mr *MockCgroupManagerMockRecorder) RemoveSandboxCgroup(sbParent, containerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSandboxCgroup", reflect.TypeOf((*MockCgroupManager)(nil).RemoveSandboxCgroup), sbParent, containerID)
}

// SandboxCgroupManager mocks base method.
func (m *MockCgroupManager) SandboxCgroupManager(sbParent, sbID string) (cgroups.Manager, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SandboxCgroupManager", sbParent, sbID)
	ret0, _ := ret[0].(cgroups.Manager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SandboxCgroupManager indicates an expected call of SandboxCgroupManager.
func (mr *MockCgroupManagerMockRecorder) SandboxCgroupManager(sbParent, sbID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SandboxCgroupManager", reflect.TypeOf((*MockCgroupManager)(nil).SandboxCgroupManager), sbParent, sbID)
}

// SandboxCgroupPath mocks base method.
func (m *MockCgroupManager) SandboxCgroupPath(arg0, arg1 string, arg2 int64) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SandboxCgroupPath", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SandboxCgroupPath indicates an expected call of SandboxCgroupPath.
func (mr *MockCgroupManagerMockRecorder) SandboxCgroupPath(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SandboxCgroupPath", reflect.TypeOf((*MockCgroupManager)(nil).SandboxCgroupPath), arg0, arg1, arg2)
}

// SandboxCgroupStats mocks base method.
func (m *MockCgroupManager) SandboxCgroupStats(sbParent, sbID string) (*stats.CgroupStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SandboxCgroupStats", sbParent, sbID)
	ret0, _ := ret[0].(*stats.CgroupStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SandboxCgroupStats indicates an expected call of SandboxCgroupStats.
func (mr *MockCgroupManagerMockRecorder) SandboxCgroupStats(sbParent, sbID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SandboxCgroupStats", reflect.TypeOf((*MockCgroupManager)(nil).SandboxCgroupStats), sbParent, sbID)
}
