#!/usr/bin/env bash
set -euo pipefail

. /etc/os-release

install_packages_ubuntu() {
    CRIU_REPO="https://download.opensuse.org/repositories/devel:/tools:/criu/xUbuntu_$VERSION_ID"

    curl -fSsL "$CRIU_REPO/Release.key" | sudo apt-key add -
    echo "deb $CRIU_REPO/ /" | sudo tee /etc/apt/sources.list.d/criu.list

    sudo apt update
    sudo apt install -y \
        autoconf \
        automake \
        cargo \
        conmon \
        criu \
        libaio-dev \
        libapparmor-dev \
        libbtrfs-dev \
        libcap-dev \
        libdevmapper-dev \
        libfuse-dev \
        libgpgme11-dev \
        libjson-c-dev \
        libnet1-dev \
        libnl-3-dev \
        libprotobuf-c-dev \
        libprotobuf-dev \
        libseccomp-dev \
        libsystemd-dev \
        libtool \
        libudev-dev \
        libyajl-dev \
        lld \
        make \
        rustc \
        sed \
        socat \
        uuid-dev \
        wget
}

install_packages_rhel() {
    sudo dnf install -y \
        autoconf \
        automake \
        conntrack-tools \
        container-selinux \
        criu \
        device-mapper-devel \
        gcc \
        git-core \
        glib2-devel \
        glibc-devel \
        gpgme-devel \
        iproute \
        json-c-devel \
        iptables \
        libassuan-devel \
        libcap-devel \
        libseccomp-devel \
        libselinux-devel \
        libtool \
        make \
        nmap-ncat \
        pkgconf-pkg-config \
        sed \
        socat \
        systemd-devel \
        wget
}

case "$ID" in
    ubuntu)
        install_packages_ubuntu
        ;;
    rhel | centos)
        install_packages_rhel
        ;;
    *)
        echo "Unsupported distribution: $ID"
        exit 1
        ;;
esac
