// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cri-o/cri-o/internal/ociartifact/datastore (interfaces: Impl,LibartifactStore)
//
// Generated by this command:
//
//	mockgen -package datastoremock -destination ./test/mocks/ociartifact/datastore/datastore.go github.com/cri-o/cri-o/internal/ociartifact/datastore Impl,LibartifactStore
//

// Package datastoremock is a generated GoMock package.
package datastoremock

import (
	context "context"
	reflect "reflect"

	digest "github.com/opencontainers/go-digest"
	libimage "go.podman.io/common/libimage"
	libartifact "go.podman.io/common/pkg/libartifact"
	types "go.podman.io/common/pkg/libartifact/types"
	gomock "go.uber.org/mock/gomock"
)

// MockImpl is a mock of Impl interface.
type MockImpl struct {
	ctrl     *gomock.Controller
	recorder *MockImplMockRecorder
	isgomock struct{}
}

// MockImplMockRecorder is the mock recorder for MockImpl.
type MockImplMockRecorder struct {
	mock *MockImpl
}

// NewMockImpl creates a new mock instance.
func NewMockImpl(ctrl *gomock.Controller) *MockImpl {
	mock := &MockImpl{ctrl: ctrl}
	mock.recorder = &MockImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImpl) EXPECT() *MockImplMockRecorder {
	return m.recorder
}

// NewArtifactReference mocks base method.
func (m *MockImpl) NewArtifactReference(arg0 string) (libartifact.ArtifactReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewArtifactReference", arg0)
	ret0, _ := ret[0].(libartifact.ArtifactReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewArtifactReference indicates an expected call of NewArtifactReference.
func (mr *MockImplMockRecorder) NewArtifactReference(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewArtifactReference", reflect.TypeOf((*MockImpl)(nil).NewArtifactReference), arg0)
}

// ReadFile mocks base method.
func (m *MockImpl) ReadFile(arg0 string, arg1 int64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockImplMockRecorder) ReadFile(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockImpl)(nil).ReadFile), arg0, arg1)
}

// MockLibartifactStore is a mock of LibartifactStore interface.
type MockLibartifactStore struct {
	ctrl     *gomock.Controller
	recorder *MockLibartifactStoreMockRecorder
	isgomock struct{}
}

// MockLibartifactStoreMockRecorder is the mock recorder for MockLibartifactStore.
type MockLibartifactStoreMockRecorder struct {
	mock *MockLibartifactStore
}

// NewMockLibartifactStore creates a new mock instance.
func NewMockLibartifactStore(ctrl *gomock.Controller) *MockLibartifactStore {
	mock := &MockLibartifactStore{ctrl: ctrl}
	mock.recorder = &MockLibartifactStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLibartifactStore) EXPECT() *MockLibartifactStoreMockRecorder {
	return m.recorder
}

// BlobMountPaths mocks base method.
func (m *MockLibartifactStore) BlobMountPaths(ctx context.Context, asr libartifact.ArtifactStoreReference, opts *types.BlobMountPathOptions) ([]types.BlobMountPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlobMountPaths", ctx, asr, opts)
	ret0, _ := ret[0].([]types.BlobMountPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlobMountPaths indicates an expected call of BlobMountPaths.
func (mr *MockLibartifactStoreMockRecorder) BlobMountPaths(ctx, asr, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlobMountPaths", reflect.TypeOf((*MockLibartifactStore)(nil).BlobMountPaths), ctx, asr, opts)
}

// Pull mocks base method.
func (m *MockLibartifactStore) Pull(ctx context.Context, ref libartifact.ArtifactReference, opts libimage.CopyOptions) (digest.Digest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pull", ctx, ref, opts)
	ret0, _ := ret[0].(digest.Digest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pull indicates an expected call of Pull.
func (mr *MockLibartifactStoreMockRecorder) Pull(ctx, ref, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockLibartifactStore)(nil).Pull), ctx, ref, opts)
}
