#!/usr/bin/env bash
set -euo pipefail

GIT_ROOT=$(git rev-parse --show-toplevel)

ARCHIVE_PATH="$GIT_ROOT/build/bundle"
mkdir -p "$ARCHIVE_PATH"

ARCH=${1:-amd64}
ARCHIVE="cri-o.$ARCH.$(git describe --tags --exact-match 2>/dev/null || git rev-parse HEAD).tar.gz"
ARCHIVE_SHA256SUM="$ARCHIVE.sha256sum"

export ARCHIVE
export ARCHIVE_SHA256SUM
