name: patch release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
permissions:
  contents: read

jobs:
  patch-release:
    permissions:
      contents: write
      pull-requests: write
    if: github.ref == 'refs/heads/main' && github.repository == 'cri-o/cri-o'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
